
#line 3 "lex.lha.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */
#define yy_create_buffer lha_create_buffer
#define yy_delete_buffer lha_delete_buffer
#define yy_flex_debug lha_flex_debug
#define yy_init_buffer lha_init_buffer
#define yy_flush_buffer lha_flush_buffer
#define yy_load_buffer_state lha_load_buffer_state
#define yy_switch_to_buffer lha_switch_to_buffer
#define yyin lhain
#define yyleng lhaleng
#define yylex lhalex
#define yylineno lhalineno
#define yyout lhaout
#define yyrestart lharestart
#define yytext lhatext
#define yywrap lhawrap
#define yyalloc lhaalloc
#define yyrealloc lharealloc
#define yyfree lhafree

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE lharestart(lhain  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int lhaleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *lhain, *lhaout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up lhatext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up lhatext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via lharestart()), so that the user can continue scanning by
	 * just pointing lhain at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when lhatext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int lhaleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow lhawrap()'s to do buffer switches
 * instead of setting up a fresh lhain.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void lharestart (FILE *input_file  );
void lha_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE lha_create_buffer (FILE *file,int size  );
void lha_delete_buffer (YY_BUFFER_STATE b  );
void lha_flush_buffer (YY_BUFFER_STATE b  );
void lhapush_buffer_state (YY_BUFFER_STATE new_buffer  );
void lhapop_buffer_state (void );

static void lhaensure_buffer_stack (void );
static void lha_load_buffer_state (void );
static void lha_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER lha_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE lha_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE lha_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE lha_scan_bytes (yyconst char *bytes,int len  );

/* %endif */

void *lhaalloc (yy_size_t  );
void *lharealloc (void *,yy_size_t  );
void lhafree (void *  );

#define yy_new_buffer lha_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        lhaensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            lha_create_buffer(lhain,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        lhaensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            lha_create_buffer(lhain,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] lhatext/lhain/lhaout/yy_state_type/lhalineno etc. def's & init go here */
/* Begin user sect3 */

#define lhawrap(n) 1
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *lhain = (FILE *) 0, *lhaout = (FILE *) 0;

typedef int yy_state_type;

extern int lhalineno;

int lhalineno = 1;

extern char *lhatext;
#define yytext_ptr lhatext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up lhatext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle lhatext and lhaleng for yymore() goes here \ */\
	lhaleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to lhatext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[188] =
    {   0,
       51,   51,   55,   54,    1,    2,   14,    7,   54,   12,
       10,   11,   21,   22,    6,   23,   54,   20,   51,    8,
        5,   18,   17,   19,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,    9,   24,   53,   53,   53,   53,
       53,   53,    4,   13,    1,    2,    0,    3,   52,    0,
       51,    0,   15,   16,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,    0,   52,   43,
       47,   53,   53,   53,   53,   53,   53,   53,   53,   46,
       53,   45,   53,   53,   53,   50,   38,   53,   53,   53,

       35,   40,   39,   53,   53,   53,   53,   53,   44,   53,
       53,   49,   53,   53,   41,   53,   53,   53,   53,   34,
       42,   53,   53,   53,   53,   53,   53,   53,   53,   26,
       53,   37,   53,   53,   53,   53,   53,   53,   53,   53,
       36,   53,   53,   53,   25,   53,   53,   53,   53,   53,
       53,   48,   53,   53,   53,   53,   53,   53,   33,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   27,   28,   53,   53,   53,   53,   53,   53,   53,
       30,   29,   32,   53,   53,   31,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   22,   23,   23,   23,   24,   25,
       26,   23,   27,   23,   23,   28,   29,   30,   23,   23,
       23,   31,   32,   33,   34,   35,   23,   23,   23,   23,
        1,   36,    1,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   23,   23,   48,   49,   50,
       51,   23,   23,   52,   53,   54,   55,   23,   23,   56,
       23,   23,   57,   58,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[59] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    1,    1
    } ;

static yyconst flex_int16_t yy_base[190] =
    {   0,
        0,    0,  217,  218,  214,  212,  218,  218,  211,  218,
      218,  218,  218,  218,  218,  218,  197,  218,   45,  218,
      218,  192,  218,  191,   32,    0,  168,   40,  159,   24,
       25,  168,  176,  167,  218,  218,  165,  153,  152,  154,
      151,   26,  218,  218,  198,  196,  195,  218,   50,  181,
       62,   66,  218,  218,    0,  168,  169,  149,  165,  142,
       36,  138,  151,  148,  132,  148,  136,   56,  151,  132,
      130,  132,  126,  129,  125,  122,  127,  160,  159,    0,
        0,  131,  141,  133,  117,  127,  115,  138,  128,    0,
      116,    0,  114,  125,  139,  115,    0,  108,  120,  108,

        0,    0,    0,  105,  133,  108,  108,  109,    0,  114,
       98,    0,  110,   98,    0,  110,   94,   99,   94,    0,
        0,  117,  105,   91,   93,   94,  101,   92,   98,    0,
       94,    0,   85,   87,   95,   90,   81,   77,   91,   81,
        0,   87,   99,   78,    0,   75,   77,   83,   79,   82,
       69,    0,   66,   67,   69,   63,   61,   73,   85,   62,
       68,   82,   62,   69,   57,   50,   49,   54,   49,   45,
       45,    0,    0,   44,   46,   48,   40,   38,   36,   34,
        0,    0,    0,   31,   27,    0,  218,  105,   69
    } ;

static yyconst flex_int16_t yy_def[190] =
    {   0,
      187,    1,  187,  187,  187,  187,  187,  187,  188,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  187,  187,  189,  189,  189,  189,
      189,  189,  187,  187,  187,  187,  188,  187,  187,  187,
      187,  187,  187,  187,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  187,  187,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,    0,  187,  187
    } ;

static yyconst flex_int16_t yy_nxt[277] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   26,   29,   30,   31,   32,
       26,   26,   33,   26,   34,   35,   36,    4,   37,   26,
       38,   39,   26,   40,   26,   26,   41,   26,   42,   26,
       26,   26,   26,   26,   26,   26,   43,   44,   50,   56,
       51,   59,   62,   65,   76,   49,   57,   66,   52,   63,
       55,   67,   77,   52,   64,   50,   78,   51,   78,  186,
      185,   79,   85,   93,  184,   52,   60,   52,  183,   86,
       94,  182,   52,  181,  180,  179,  178,  177,  176,  175,

      174,  173,  172,  171,   52,   47,   47,  170,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  130,  129,  128,
      127,  126,  125,  124,  123,  122,  121,  120,  119,  118,
      117,  116,  115,  114,  113,  112,  111,  110,  109,  108,
      107,  106,  105,  104,   79,   79,  103,  102,  101,  100,
       99,   98,   97,   96,   95,   92,   91,   90,   89,   88,
       87,   84,   83,   82,   81,   80,   49,   48,   46,   45,

       75,   74,   73,   72,   71,   70,   69,   68,   61,   58,
       54,   53,   49,   48,   46,   45,  187,    3,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187
    } ;

static yyconst flex_int16_t yy_chk[277] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   19,   25,
       19,   28,   30,   31,   42,   49,   25,   31,   19,   30,
      189,   31,   42,   49,   30,   51,   52,   51,   52,  185,
      184,   52,   61,   68,  180,   51,   28,   19,  179,   61,
       68,  178,   49,  177,  176,  175,  174,  171,  170,  169,

      168,  167,  166,  165,   51,  188,  188,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  151,
      150,  149,  148,  147,  146,  144,  143,  142,  140,  139,
      138,  137,  136,  135,  134,  133,  131,  129,  128,  127,
      126,  125,  124,  123,  122,  119,  118,  117,  116,  114,
      113,  111,  110,  108,  107,  106,  105,  104,  100,   99,
       98,   96,   95,   94,   93,   91,   89,   88,   87,   86,
       85,   84,   83,   82,   79,   78,   77,   76,   75,   74,
       73,   72,   71,   70,   69,   67,   66,   65,   64,   63,
       62,   60,   59,   58,   57,   56,   50,   47,   46,   45,

       41,   40,   39,   38,   37,   34,   33,   32,   29,   27,
       24,   22,   17,    9,    6,    5,    3,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int lha_flex_debug;
int lha_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[54] =
    {   0,
       36,   37,   38,   44,   46,   49,   52,   55,   58,   61,
       63,   65,   67,   69,   72,   74,   77,   79,   81,   85,
       87,   89,   91,   93,   96,  101,  104,  107,  110,  113,
      116,  119,  122,  125,  130,  133,  136,  139,  143,  146,
      149,  152,  155,  158,  161,  164,  167,  170,  173,  176,
      180,  187,  195
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *lhatext;
#line 1 "Lha-scanner.ll"
#line 2 "Lha-scanner.ll"
# include <cstdlib>
# include <errno.h>
# include <limits.h>
# include <string>
# include "Lha-Reader.hpp"
# include "Lha-parser.tab.hh"


# undef lhawrap
# define lhawrap() 1

# define YY_DECL LHA_DECL

/* By default lhalex returns int, we use token_type.
   Unfortunately lhaterminate by default returns 0, which is
   not of token_type.  */
#define yyterminate() return token::END
#line 30 "Lha-scanner.ll"
# define LHA_USER_ACTION  lhalloc->columns (lhaleng);
#line 703 "lex.lha.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int lhalex_destroy (void );

int lhaget_debug (void );

void lhaset_debug (int debug_flag  );

YY_EXTRA_TYPE lhaget_extra (void );

void lhaset_extra (YY_EXTRA_TYPE user_defined  );

FILE *lhaget_in (void );

void lhaset_in  (FILE * in_str  );

FILE *lhaget_out (void );

void lhaset_out  (FILE * out_str  );

int lhaget_leng (void );

char *lhaget_text (void );

int lhaget_lineno (void );

void lhaset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int lhawrap (void );
#else
extern int lhawrap (void );
#endif
#endif

/* %not-for-header */

/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( lhatext, lhaleng, 1, lhaout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( lhain )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( lhain ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, lhain))==0 && ferror(lhain)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(lhain); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int lhalex (void);

#define YY_DECL int lhalex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after lhatext and lhaleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 32 "Lha-scanner.ll"


  lhalloc->step ();

#line 948 "lex.lha.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! lhain )
/* %if-c-only */
			lhain = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! lhaout )
/* %if-c-only */
			lhaout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			lhaensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				lha_create_buffer(lhain,YY_BUF_SIZE );
		}

		lha_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of lhatext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 188 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 187 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for lhalineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( lha_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 54 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], lhatext );
			else if ( yy_act == 54 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         lhatext );
			else if ( yy_act == 55 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "Lha-scanner.ll"
lhalloc->step ();
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 37 "Lha-scanner.ll"
lhalloc->lines (lhaleng); lhalloc->step ();
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 38 "Lha-scanner.ll"

	YY_BREAK

  typedef lha::Lha_parser::token token;

/* Convert ints to the actual type of tokens.  */
case 4:
YY_RULE_SETUP
#line 44 "Lha-scanner.ll"
return lha::Lha_parser::token_type (lhatext[0]);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::SEMICOLON;
            Reader.error (*lhalloc, "; expected");} 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 49 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::COMMA;
            Reader.error (*lhalloc, ", expected");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::SHARP;
            Reader.error (*lhalloc, "# expected");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 55 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::COLON;
            Reader.error (*lhalloc, ": expected");}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 58 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::BackSlash;
            Reader.error (*lhalloc, "\\ expected");}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::LB;
            Reader.error (*lhalloc, "( expected");}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::RB;
            Reader.error (*lhalloc, ") expected");}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::AND;
            Reader.error (*lhalloc, "& expected");}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::OR;
            Reader.error (*lhalloc, "| expected");}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 69 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::NOT;
            Reader.error (*lhalloc, "! expected");}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 72 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::LEQ;
            Reader.error (*lhalloc, "<= expected");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 74 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::GEQ;
            Reader.error (*lhalloc, ">= expected");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::EQ;
            Reader.error (*lhalloc, "= expected");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 79 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::LL;
            Reader.error (*lhalloc, "< expected");}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::GG;
            Reader.error (*lhalloc, "> expected");}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 85 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::DIV;
            Reader.error (*lhalloc, "/ expected");}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 87 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::MUL;
            Reader.error (*lhalloc, "* expected");}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 89 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::PLUS;
            Reader.error (*lhalloc, "+ expected");}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 91 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::MINUS;
            Reader.error (*lhalloc, "- expected");}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 93 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::POWER;
            Reader.error (*lhalloc, "^ expected");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 96 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::LhaName;
            Reader.error (*lhalloc, "LhaName expected");}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 101 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::Const;
            Reader.error (*lhalloc, "const expected");}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 104 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::NbLoc;
            Reader.error (*lhalloc, "NbLocations expected");}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 107 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::NbVar;
            Reader.error (*lhalloc, "NbVariables expected");}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::VList;
            Reader.error (*lhalloc, "VariablesList expected");}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 113 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::LList;
            Reader.error (*lhalloc, "LocationsList expected");}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 116 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::Iloc;
            Reader.error (*lhalloc, "InitialLocations expected");}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 119 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::Floc;
            Reader.error (*lhalloc, "FinalLocations expected");}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 122 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::locations;
            Reader.error (*lhalloc, "Locations expected");}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 125 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::edges;
            Reader.error (*lhalloc, "Edges expected");}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 130 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::INT;
            Reader.error (*lhalloc, "int expected");}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 133 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::DOUBLE;
            Reader.error (*lhalloc, "double expected");}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 136 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::FLOOR;
            Reader.error (*lhalloc, "floor expected");}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 139 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::ABS;
            Reader.error (*lhalloc, "abs expected");}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 143 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::MIN;
            Reader.error (*lhalloc, "min expected");}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 146 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::MAX;
            Reader.error (*lhalloc, "max expected");}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 149 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::TRUE;
            Reader.error (*lhalloc, "TRUE expected");}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 152 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::FALSE;
            Reader.error (*lhalloc, "FALSE expected");}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 155 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::ALL;
            Reader.error (*lhalloc, "ALL expected");}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 158 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::LAST;
            Reader.error (*lhalloc, "Last expected");}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 161 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::LhaMIN;
            Reader.error (*lhalloc, "Min expected");}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 164 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::LhaMAX;
            Reader.error (*lhalloc, "Max expected");}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 167 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::AVG;
            Reader.error (*lhalloc, "AVG expected");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 170 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::INTEGRAL;
            Reader.error (*lhalloc, "Integral expected");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 173 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::MEAN;
            Reader.error (*lhalloc, "Mean expected");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 176 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::VAR;
            Reader.error (*lhalloc, "Var expected");}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 180 "Lha-scanner.ll"
{
  errno = 0; 
  int x=atoi(lhatext);
  lhalval->IntVal = x;
  return token::ival;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 187 "Lha-scanner.ll"
{
  errno = 0; 
  double x=atof(lhatext);
  lhalval->RealVal = x;
  return token::rval;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 195 "Lha-scanner.ll"
{lhalval->name = new std::string (lhatext); return token::str;
            Reader.error (*lhalloc, "invalid character");}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 198 "Lha-scanner.ll"
ECHO;
	YY_BREAK
#line 1391 "lex.lha.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed lhain at a new source and called
			 * lhalex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = lhain;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( lhawrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * lhatext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of lhalex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					lharealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			lharestart(lhain  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) lharealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 188 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 188 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 187);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					lharestart(lhain );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( lhawrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve lhatext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and lhalineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void lharestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        lhaensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            lha_create_buffer(lhain,YY_BUF_SIZE );
	}

	lha_init_buffer(YY_CURRENT_BUFFER,input_file );
	lha_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void lha_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		lhapop_buffer_state();
	 *		lhapush_buffer_state(new_buffer);
     */
	lhaensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	lha_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (lhawrap()) processing, but the only time this flag
	 * is looked at is after lhawrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void lha_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	lhain = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE lha_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) lhaalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in lha_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) lhaalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in lha_create_buffer()" );

	b->yy_is_our_buffer = 1;

	lha_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with lha_create_buffer()
 * 
 */
/* %if-c-only */
    void lha_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		lhafree((void *) b->yy_ch_buf  );

	lhafree((void *) b  );
}

/* %if-c-only */

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* %endif */

/* %if-c++-only */
/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a lharestart() or at EOF.
 */
/* %if-c-only */
    static void lha_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	lha_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then lha_init_buffer was _probably_
     * called from lharestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void lha_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		lha_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void lhapush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	lhaensure_buffer_stack();

	/* This block is copied from lha_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from lha_switch_to_buffer. */
	lha_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void lhapop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	lha_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		lha_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void lhaensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)lhaalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in lhaensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)lharealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in lhaensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE lha_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) lhaalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in lha_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	lha_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to lhalex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       lha_scan_bytes() instead.
 */
YY_BUFFER_STATE lha_scan_string (yyconst char * yystr )
{
    
	return lha_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to lhalex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE lha_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) lhaalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in lha_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = lha_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in lha_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up lhatext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		lhatext[lhaleng] = (yy_hold_char); \
		(yy_c_buf_p) = lhatext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		lhaleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int lhaget_lineno  (void)
{
        
    return lhalineno;
}

/** Get the input stream.
 * 
 */
FILE *lhaget_in  (void)
{
        return lhain;
}

/** Get the output stream.
 * 
 */
FILE *lhaget_out  (void)
{
        return lhaout;
}

/** Get the length of the current token.
 * 
 */
int lhaget_leng  (void)
{
        return lhaleng;
}

/** Get the current token.
 * 
 */

char *lhaget_text  (void)
{
        return lhatext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void lhaset_lineno (int  line_number )
{
    
    lhalineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see lha_switch_to_buffer
 */
void lhaset_in (FILE *  in_str )
{
        lhain = in_str ;
}

void lhaset_out (FILE *  out_str )
{
        lhaout = out_str ;
}

int lhaget_debug  (void)
{
        return lha_flex_debug;
}

void lhaset_debug (int  bdebug )
{
        lha_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from lhalex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    lhain = stdin;
    lhaout = stdout;
#else
    lhain = (FILE *) 0;
    lhaout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * lhalex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* lhalex_destroy is for both reentrant and non-reentrant scanners. */
int lhalex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		lha_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		lhapop_buffer_state();
	}

	/* Destroy the stack itself. */
	lhafree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * lhalex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *lhaalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *lharealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void lhafree (void * ptr )
{
	free( (char *) ptr );	/* see lharealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 198 "Lha-scanner.ll"






void
Lha_Reader::scan_end ()
{  
  lhalex_destroy();
}


void Lha_Reader::scan_expression (const string& f){
  const char* ch=f.c_str();
lhaset_debug(trace_scanning);

 lha_scan_string(ch);
 
}


