


all:
	(cd TandemQN && ocaml test.ml)
	(cd pi && ocaml test.ml)
	(cd Workflow-Net && ocaml test.ml)
	(cd QueueMM1 && ocaml test.ml)
	(cd RareEventUnbounded && ocaml test.ml)
	(cd DataBase && ocaml test.ml)
	(cd RareEventUnbounded && ocaml test2.ml)
	(cd TandemCosy && ocaml testPrism.ml)
	(cd RareEventU && ocaml test.ml)