before_script:
  - eval `opam config env`

stages:
  - configure
  - build
  - test

configure:
    stage: configure
    script:
      - rm -rf build
      - autoreconf --install
      - mkdir build
      - cd build
      - ../configure --prefix=`pwd`/../ LEX=/usr/local/Cellar/flex/2.5.39/bin/flex YACC=/usr/local/Cellar/bison/3.0.4/bin/bison

Cosmos:
  stage: build
  script:
    - cd build
    - make -j 4
    - make install    

modelConvert:
  stage: build
  script:
    - cd prism2SPT
    - ./build.sh
    
test:
  stage: test
  script:
    - cd Examples
    - ocaml bench.ml