image: registry.git.lacl.fr/barbot/cosmos:latest

before_script:
  - eval `opam config env`
  - export PATH=/usr/local/Cellar/flex/2.5.39/bin:/usr/local/Cellar/bison/3.0.4/bin:$PATH

stages:
  - build
  - test

cmake-build:
  stage: build
  script:
    - mkdir -p build-cmake
    - cd build-cmake
    - cmake ../
    - make -j 4
  allow_failure: true

from_dist:
    stage: test
    script:
     - mkdir -p build-dist
     - cd build-dist
     - cp ../build/cosmos-1.5.tar.gz ./
     - tar xzvf cosmos-1.5.tar.gz
     - cd cosmos-1.5.tar.gz
     - ./configure --enable-silent-rules
     - make -j 4

Cosmos:
  stage: build
  script:
    - rm -rf build
    - autoreconf --install
    - mkdir build
    - cd build
    - ../configure --prefix=`pwd`/../ --enable-silent-rules
    - make -j 4
    - make install
    - make dist
  artifacts:
    paths:
      - bin/
      - lib/
      - include/
      - build/cosmos-1.5.tar.gz
  cache:
    paths:
      - bin/
      - lib/
      - include/

modelConvert:
  stage: build
  script:
    - mkdir -p bin
    - cd modelConvert
    - ./build.sh
  artifacts:
    paths:
      - bin/
  cache:
    paths:
      - bin/
    
test:
  stage: test
  script:
    - echo `pwd`
    - cd Examples
    - ocaml bench.ml