before_script:
  - eval `opam config env`

stages:
  - build
  - test

cmake-build:
  stage: build
  script:
    - mkdir -p build-cmake
    - cd build-cmake
    - cmake ../
    - make -j 4


Cosmos:
  stage: build
  script:
    - rm -rf build
    - autoreconf --install
    - mkdir build
    - cd build
    - ../configure --prefix=`pwd`/../ LEX=/usr/local/Cellar/flex/2.5.39/bin/flex YACC=/usr/local/Cellar/bison/3.0.4/bin/bison --enable-silent-rules
    - make -j 4
    - make install    
  artifacts:
    paths:
      - bin/
      - lib/
      - include/
  cache:
    paths:
      - bin/
      - lib/
      - include/

modelConvert:
  stage: build
  script:
    - mkdir -p bin
    - cd prism2SPT
    - ./build.sh
  artifacts:
    paths:
      - bin/
  cache:
    paths:
      - bin/
    
test:
  stage: test
  script:
    - echo `pwd`
    - cd Examples
    - ocaml bench.ml