before_script:
  - eval `opam config env`

build:
  script:
    - rm -rf build
    - autoreconf --install
    - mkdir build
    - cd build
    - ../configure --prefix=`pwd`/../ LEX=/usr/local/Cellar/flex/2.5.39/bin/flex YACC=/usr/local/Cellar/bison/3.0.4/bin/bison
    - make