#!/bin/bash

cd ../modelConvert/
./test.sh
cd ../testMC/

cp ../modelConvert/SKModel.cpp ./
cp ../modelConvert/SKModel.hpp ./
cp ../modelConvert/markingImpl.hpp ./
cp ../modelConvert/SKModel.grml ./
cp ../modelConvert/SKModelCommons.cpp ./

g++ -Wno-return-type -std=gnu++11 -c -I/usr/local/include -I../include -o main.o main.cpp
g++ -Wno-return-type -std=gnu++11 -c -I/usr/local/include -I../include -o LHA.o LHA.cpp
g++ -Wno-return-type -std=gnu++11 -I/usr/local/include -o ClientSim LHA.o main.o ../lib/libClientSimBase.a
