function [ delayTab, heightTab, widthTab] = extractDelay( R_data,S_data,T_data,Q_data,P_data,rate )
%EXTRACTDELAY Summary of this function goes here
%   Detailed explanation goes here

minT = P_data(1,1);
maxT = T_data(length(T_data),1);

P_data = filterOut(minT,maxT,P_data);
Q_data = filterOut(minT,maxT,Q_data);
R_data = filterOut(minT,maxT,R_data);
S_data = filterOut(minT,maxT,S_data);
T_data = filterOut(minT,maxT,T_data);




delayTab = [ (P_data(1:end,1) - [0.0; P_data(1:end-1,1)]) ...
            ,(Q_data(:,1)-P_data(:,1)) ...
            ,(R_data(:,1)-P_data(:,1)) ...
            ,(S_data(:,1)-P_data(:,1)) ...
            ,(T_data(:,1)-P_data(:,1))]/rate;
        
heightTab = [ P_data(:,2) ...
            , Q_data(:,2) ...
            , R_data(:,2) ...
            , S_data(:,2) ...
            , T_data(:,2) ];
   
widthTab  = [ P_data(:,3) ...
            , Q_data(:,3) ...
            , R_data(:,3) ...
            , S_data(:,3) ...
            , T_data(:,3) ]/rate;
        
end

