% MOEA_CPR   MOEA and SPEA2 copyright statements
%
% MOEA  - Multi-Objective Evolutionary Algorithm
% SPEA2 - Strength Pareto Evolutionary Algorithm 2, developed under PISA
% PISA  - Platform and Programming Language Independent Interface for Search Algorithms
%
% PISA  (www.tik.ee.ethz.ch/pisa/)
% Computer Engineering (TIK) ETH Zurich
% ======================================================================
%                   PISA Copyright and Legal Statements
%
% Copyright (c) 2002-2003 Swiss Federal Institute of Technology,
% Computer Engineering and Networks Laboratory. All rights reserved.
%
% IN NO EVENT SHALL THE SWISS FEDERAL INSTITUTE OF TECHNOLOGY, COMPUTER
% ENGINEERING AND NETWORKS LABORATORY BE LIABLE TO ANY PARTY FOR DIRECT,
% INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF
% THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE SWISS
% FEDERAL INSTITUTE OF TECHNOLOGY, COMPUTER ENGINEERING AND NETWORKS
% LABORATORY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
%  
% THE SWISS FEDERAL INSTITUTE OF TECHNOLOGY, COMPUTER ENGINEERING AND
% NETWORKS LABORATORY, SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,
% BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
% FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
% AN "AS IS" BASIS, AND THE SWISS FEDERAL INSTITUTE OF TECHNOLOGY,
% COMPUTER ENGINEERING AND NETWORKS LABORATORY HAS NO OBLIGATION TO
% PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
%
%
%
% Likewise the original license, the MATLAB implementation of SPEA 2
% is developed and distributed under the following license agreement.
%
% MOEA: Combined MATLAB - C implementation of SPEA 2
% Hamburg University of Technology
% Institute of Control Systems
% http://www.tu-harburg.de/rts
% ======================================================================
%                 MOEA-SPEA Copyright and Legal Statements
%
% IN NO EVENT SHALL THE HAMBURG UNIVERSITY OF TECHNOLOGY, INSTITUTE OF
% CONTROL SYSTEMS BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL,
% INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OF THIS
% SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE HAMBURG UNIVERSITY OF
% TECHNOLOGY, INSTITUTE OF CONTROL SYSTEMS HAS BEEN ADVISED OF THE
% POSSIBILITY OF SUCH DAMAGE.
%  
% HAMBURG UNIVERSITY OF TECHNOLOGY, INSTITUTE OF CONTROL SYSTEMS,
% SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
% IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
% PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE
% HAMBURG UNIVERSITY OF TECHNOLOGY, INSTITUTE OF CONTROL SYSTEMS HAS NO
% OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR
% MODIFICATIONS.
%
% 2005-2007 Hamburg University of Technology, Institute of Control Systems
function moea_copyrights()

help spea2_cpr
