function writeExampleFile2D(nonLinearConstrainsFile, ranges, paramNames, experimentName)
content = {...
'<?xml version="1.0" encoding="ISO-8859-1" ?>';...
'<Simulator>';...
	strcat('<Name>two_params_',experimentName,'</Name>');...
	'<Description>';...
	strcat('Two parameters GP, experiment: ',experimentName);...
	'</Description>';...
	'<!-- The input parameters -->';...
	'<InputParameters>';...
    strcat('<Parameter name="',paramNames{1},'" type="real" minimum="', sprintf('%f',ranges(1,1)),...
    '" maximum="', sprintf('%f',ranges(1,2)),'"/>');...
    strcat('<Parameter name="',paramNames{2},'" type="real" minimum="', sprintf('%f',ranges(2,1)),...
    '" maximum="', sprintf('%f',ranges(2,2)),'"/>');...
	'<Constraint type="NonlinearConstraint" >';...
	strcat('<Option key="f" value="',nonLinearConstrainsFile,'" />');...
	'	</Constraint>  ';...
	'</InputParameters>';...
	'<!-- The output parameters -->';...
	'<OutputParameters>';...
	'	<Parameter name="out" type="real"/>';...
	'</OutputParameters>';...
	'<!-- A simulator may have multiple implementations: as an executable, a ';...
	'     java main class, a dataset, ...-->';...
	'<Implementation>';...
	'	<Executables>';...
	'		<!-- An arch attribute may make sense here as well -->';...
	'		<Executable platform="matlab">computeVal</Executable>';...
	'	</Executables>';...
	'</Implementation>';...
'</Simulator>'};

file1 = fopen('examples/TwoParams/twoparams.xml','w');
file2 = fopen(strcat('examples/TwoParams/twoparams_',experimentName,'.xml'),'w');

for i=1:size(content,1)
    fprintf(file1,'%s\n',content{i});
    fprintf(file2,'%s\n',content{i});
end


fclose(file1);
fclose(file2);
end