function writeExampleFile1D(nonLinearConstrainsFile, range, paramName, experimentName)

content = {...
'<?xml version="1.0" encoding="ISO-8859-1" ?>';...
'<Simulator>';...
	'<Name>one_param</Name>';...
	'<Description>';...
	strcat('One parameter GP, experiment: ',experimentName);...
	'</Description>';...
	'<!-- The input parameter -->';...
	'<InputParameters>';...
    strcat('<Parameter name="',paramName,'" type="real" minimum="', sprintf('%f',range(1)),...
    '" maximum="', sprintf('%f',range(2)),'"/>');...
	'<Constraint type="NonlinearConstraint" >';...
	strcat('<Option key="f" value="',nonLinearConstrainsFile,'" />');...
	'	</Constraint>  ';...
	'</InputParameters>';...
	'<!-- The output parameters -->';...
	'<OutputParameters>';...
	'	<Parameter name="out" type="real"/>';...
	'</OutputParameters>';...
	'<!-- A simulator may have multiple implementations: as an executable, a ';...
	'     java main class, a dataset, ...-->';...
	'<Implementation>';...
	'	<Executables>';...
	'		<!-- An arch attribute may make sense here as well -->';...
	'		<Executable platform="matlab">computeVal</Executable>';...
	'	</Executables>';...
	'</Implementation>';...
'</Simulator>'};

file1 = fopen('examples/OneParam/oneparam.xml','w');
file2 = fopen(strcat('examples/OneParam/oneparam_',experimentName,'.xml'),'w');

for i=1:size(content,1)
    fprintf(file1,'%s\n',content{i});
    fprintf(file2,'%s\n',content{i});
end

fclose(file1);
fclose(file2);
end